import { Inter } from "next/font/google";
import "./global.css";

import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Join INSTALL </title>
      </head>
      <ClerkProvider>
        <body className={`${inter.className} `}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
